Stat server has been created
alextim1508/java-explore-with-me pull request #3
Opened 2023-02-14 17:59 UTC by alextim1508

2023-02-14 20:07 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-02-14 20:07 UTC, FanaticFiz commented on stat/statClient/src/main/java/ru/practicum/explorewithme/statClient/client/StatClient.java
> +package ru.practicum.explorewithme.statClient.client;
Не корректное, с точки зрения Java naming convention, именование пакета!
Допускается дефис  `stat-client`

2023-02-14 20:07 UTC, FanaticFiz commented on stat/statCore/src/main/java/ru/practicum/explorewithme/core/dto/HitDto.java
> +package ru.practicum.explorewithme.core.dto;
А почему этот пакет называется `core` ?
Это же по содержанию пакет с `dto`. 

`stats-dto` ?

2023-02-14 20:07 UTC, FanaticFiz commented on stat/statServer/src/main/java/ru/practicum/explorewithme/statServer/config/ObjectMapperConfig.java
> +        return Jackson2ObjectMapperBuilder.json()
Есть хорошая практика делать отступ, в виде пустой строки, перед `return`.

Это выделяет точку выхода из метода визуально.
Есть только одно исключение: если метод начался сразу с return то отступ делать не нужно.

2023-02-14 20:07 UTC, FanaticFiz commented on stat/statServer/src/main/resources/application.yml
> +
Неадекватное кол-во пустых строк это тоже нарушение code-style

2023-02-14 20:13 UTC, alextim1508 commented on stat/statCore/src/main/java/ru/practicum/explorewithme/core/dto/HitDto.java
> +package ru.practicum.explorewithme.core.dto;
Сам пакет, где содержится dto сущности называется dto. Пакет на уровень выше - core. На будущее создал такой пакет. Вдруг нам понадобится что-то добавить общее для главного сервера и сервера статистики. Например, класс эксепшена. Тогда добавим в пакет core пакет exception

2023-02-14 20:14 UTC, alextim1508 commented on stat/statCore/src/main/java/ru/practicum/explorewithme/core/dto/HitDto.java
> +package ru.practicum.explorewithme.core.dto;
Или конфиг. Вот кстати, ObjectMapperConfig, можно было добавить в core, так как он будет использоваться и в главном сервере и сервере статистики.

2023-02-14 20:18 UTC, alextim1508 commented on stat/statClient/src/main/java/ru/practicum/explorewithme/statClient/client/StatClient.java
> +package ru.practicum.explorewithme.statClient.client;
Idea не пропускает такое название пакетов

2023-02-15 06:09 UTC, FanaticFiz commented on stat/statClient/src/main/java/ru/practicum/explorewithme/statClient/client/StatClient.java
> +package ru.practicum.explorewithme.statClient.client;
Эх... не дефис, а нижнее подчеркивание `stat_client`

2023-02-15 09:07 UTC, FanaticFiz approved these changes

2023-02-15 09:07 UTC, FanaticFiz commented on stat/statClient/src/main/java/ru/practicum/explorewithme/stat/client/StatClient.java
> +        if (params == null)
Как сюда прокралось это? ))
Выше же все if блоки нормально описаны.

В Java не принято экономить на `{}` ))

2023-02-15 09:15 UTC, merged